--
-- PostgreSQL database dump
--


-- Dumped from database version 18.4
-- Dumped by pg_dump version 18.4

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: activities; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.activities (
                                   id bigint NOT NULL,
                                   created_at timestamp(6) with time zone,
                                   message text NOT NULL,
                                   type character varying(255) NOT NULL,
                                   actor_id bigint NOT NULL,
                                   group_id bigint NOT NULL,
                                   CONSTRAINT activities_type_check CHECK (((type)::text = ANY ((ARRAY['GROUP_CREATED'::character varying, 'MEMBER_ADDED'::character varying, 'EXPENSE_ADDED'::character varying, 'EXPENSE_UPDATED'::character varying, 'EXPENSE_DELETED'::character varying, 'MEMBER_REMOVED'::character varying])::text[])))
);


--
-- Name: activities_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.activities ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.activities_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    );


--
-- Name: expenses; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.expenses (
                                 id bigint NOT NULL,
                                 amount numeric(12,2) NOT NULL,
                                 category character varying(255) NOT NULL,
                                 created_at timestamp(6) with time zone,
                                 currency character varying(3) NOT NULL,
                                 description character varying(255) NOT NULL,
                                 expense_date date NOT NULL,
                                 notes text,
                                 receipt_photo_url character varying(255),
                                 split_type character varying(255) NOT NULL,
                                 group_id bigint NOT NULL,
                                 paid_by bigint NOT NULL,
                                 added_by bigint,
                                 CONSTRAINT expenses_category_check CHECK (((category)::text = ANY ((ARRAY['FOOD'::character varying, 'TRAVEL'::character varying, 'RENT'::character varying, 'SHOPPING'::character varying, 'FUN'::character varying, 'OTHER'::character varying])::text[]))),
                                 CONSTRAINT expenses_split_type_check CHECK (((split_type)::text = ANY ((ARRAY['EQUAL'::character varying, 'UNEQUAL'::character varying, 'PERCENTAGE'::character varying])::text[])))
);


--
-- Name: expenses_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.expenses ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.expenses_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    );


--
-- Name: group_members; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.group_members (
                                      id bigint NOT NULL,
                                      joined_at timestamp(6) with time zone,
                                      group_id bigint NOT NULL,
                                      user_id bigint NOT NULL
);


--
-- Name: group_members_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.group_members ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.group_members_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    );


--
-- Name: groups; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.groups (
                               id bigint NOT NULL,
                               created_at timestamp(6) with time zone,
                               name character varying(255) NOT NULL,
                               created_by bigint NOT NULL
);


--
-- Name: groups_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    );


--
-- Name: password_reset_tokens; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.password_reset_tokens (
                                              id bigint NOT NULL,
                                              created_at timestamp(6) with time zone NOT NULL,
                                              expires_at timestamp(6) with time zone NOT NULL,
                                              token_hash character varying(64) NOT NULL,
                                              used boolean NOT NULL,
                                              user_id bigint NOT NULL
);


--
-- Name: password_reset_tokens_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.password_reset_tokens ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.password_reset_tokens_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    );


--
-- Name: settlement_records; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.settlement_records (
                                           id bigint NOT NULL,
                                           amount numeric(38,2) NOT NULL,
                                           settled_at timestamp(6) without time zone NOT NULL,
                                           from_user_id bigint NOT NULL,
                                           group_id bigint NOT NULL,
                                           to_user_id bigint NOT NULL
);


--
-- Name: settlement_records_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.settlement_records ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.settlement_records_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    );


--
-- Name: splits; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.splits (
                               id bigint NOT NULL,
                               amount numeric(12,2) NOT NULL,
                               settled boolean NOT NULL,
                               expense_id bigint NOT NULL,
                               user_id bigint NOT NULL
);


--
-- Name: splits_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.splits ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.splits_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    );


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
                              id bigint NOT NULL,
                              created_at timestamp(6) with time zone,
                              email character varying(255) NOT NULL,
                              name character varying(255) NOT NULL,
                              password character varying(255) NOT NULL,
                              phone_number character varying(15) NOT NULL,
                              upi_id character varying(255)
);


--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    );


--
-- Name: activities activities_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.activities
    ADD CONSTRAINT activities_pkey PRIMARY KEY (id);


--
-- Name: expenses expenses_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.expenses
    ADD CONSTRAINT expenses_pkey PRIMARY KEY (id);


--
-- Name: group_members group_members_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.group_members
    ADD CONSTRAINT group_members_pkey PRIMARY KEY (id);


--
-- Name: groups groups_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.groups
    ADD CONSTRAINT groups_pkey PRIMARY KEY (id);


--
-- Name: password_reset_tokens password_reset_tokens_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.password_reset_tokens
    ADD CONSTRAINT password_reset_tokens_pkey PRIMARY KEY (id);


--
-- Name: settlement_records settlement_records_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.settlement_records
    ADD CONSTRAINT settlement_records_pkey PRIMARY KEY (id);


--
-- Name: splits splits_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.splits
    ADD CONSTRAINT splits_pkey PRIMARY KEY (id);


--
-- Name: users uk6dotkott2kjsp8vw4d0m25fb7; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);


--
-- Name: users uk9q63snka3mdh91as4io72espi; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk9q63snka3mdh91as4io72espi UNIQUE (phone_number);


--
-- Name: password_reset_tokens ukajre85ybxavf1tt4omkrs5p6g; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.password_reset_tokens
    ADD CONSTRAINT ukajre85ybxavf1tt4omkrs5p6g UNIQUE (token_hash);


--
-- Name: group_members ukp940p7g0r9yihubnf6rtaheog; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.group_members
    ADD CONSTRAINT ukp940p7g0r9yihubnf6rtaheog UNIQUE (group_id, user_id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: splits fk7unbr8f7xk4s4iwwnn96s3yko; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.splits
    ADD CONSTRAINT fk7unbr8f7xk4s4iwwnn96s3yko FOREIGN KEY (expense_id) REFERENCES public.expenses(id);


--
-- Name: splits fkcxb7huewcd3k4m3whb440x58w; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.splits
    ADD CONSTRAINT fkcxb7huewcd3k4m3whb440x58w FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: settlement_records fket7y8cf2jnwrrv7p4djp9ckag; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.settlement_records
    ADD CONSTRAINT fket7y8cf2jnwrrv7p4djp9ckag FOREIGN KEY (from_user_id) REFERENCES public.users(id);


--
-- Name: expenses fkiwqbj8x69qhvj7a41f5r3xy10; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.expenses
    ADD CONSTRAINT fkiwqbj8x69qhvj7a41f5r3xy10 FOREIGN KEY (paid_by) REFERENCES public.users(id);


--
-- Name: password_reset_tokens fkk3ndxg5xp6v7wd4gjyusp15gq; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.password_reset_tokens
    ADD CONSTRAINT fkk3ndxg5xp6v7wd4gjyusp15gq FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: expenses fkk7nnwvg2pr7cl4gl6rqic0b1a; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.expenses
    ADD CONSTRAINT fkk7nnwvg2pr7cl4gl6rqic0b1a FOREIGN KEY (added_by) REFERENCES public.users(id);


--
-- Name: groups fkkhpvhy2p2c1un4krvhwnau23b; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.groups
    ADD CONSTRAINT fkkhpvhy2p2c1un4krvhwnau23b FOREIGN KEY (created_by) REFERENCES public.users(id);


--
-- Name: group_members fkkv9vlrye4rmhqjq4qohy2n5a6; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.group_members
    ADD CONSTRAINT fkkv9vlrye4rmhqjq4qohy2n5a6 FOREIGN KEY (group_id) REFERENCES public.groups(id);


--
-- Name: activities fkmfjrc8jdvy0yrr7x67qmrxkue; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.activities
    ADD CONSTRAINT fkmfjrc8jdvy0yrr7x67qmrxkue FOREIGN KEY (actor_id) REFERENCES public.users(id);


--
-- Name: settlement_records fkmqxlvt7fu0jouq2gvkir959f8; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.settlement_records
    ADD CONSTRAINT fkmqxlvt7fu0jouq2gvkir959f8 FOREIGN KEY (group_id) REFERENCES public.groups(id);


--
-- Name: expenses fkne4jfgy6h5e1gv78elj8bypb5; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.expenses
    ADD CONSTRAINT fkne4jfgy6h5e1gv78elj8bypb5 FOREIGN KEY (group_id) REFERENCES public.groups(id);


--
-- Name: group_members fknr9qg33qt2ovmv29g4vc3gtdx; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.group_members
    ADD CONSTRAINT fknr9qg33qt2ovmv29g4vc3gtdx FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: settlement_records fknukw14luk4e3woelhau1fhtkt; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.settlement_records
    ADD CONSTRAINT fknukw14luk4e3woelhau1fhtkt FOREIGN KEY (to_user_id) REFERENCES public.users(id);


--
-- Name: activities fkphmhk2nqnf0bxk1r9mb455avb; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.activities
    ADD CONSTRAINT fkphmhk2nqnf0bxk1r9mb455avb FOREIGN KEY (group_id) REFERENCES public.groups(id);


--
-- PostgreSQL database dump complete
--



